# permissions for end users to view helmextensions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: helmextension-viewer-role
rules:
- apiGroups:
  - extension.example.com
  resources:
  - helmextensions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extension.example.com
  resources:
  - helmextensions/status
  verbs:
  - get
